import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import UpgradeCard from '@/components/dashboard/upgradeCard'
import Navbar from '@/components/dashboard/navbar'
import Image from 'next/image'
import JustPosLogo from '@/public/images/JustPOS Logo.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-row'>
          <div className="flex flex-col h-[100vh] justify-between w-fit border-r gap-10 p-4">
            <div className="flex flex-col gap-10 mx-auto">
              <Image
                src={JustPosLogo}
                alt="The just point of sales system logo"
                width={150}
              />
              <Navbar />
            </div>
            <UpgradeCard />
          </div>
          <div className='w-full'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
